source 'https://github.com/CocoaPods/Specs.git'
use_modular_headers!
platform :ios, '11.0'

target 'XKNetwork_Example' do
  pod 'XKNetwork', :path => '../'

  target 'XKNetwork_Tests' do
    inherit! :search_paths
  end
  
end
